
services:

  frontend:
    image: riya9421/mern-task-manager-frontend:latest
    container_name: taskmanager-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - taskmanager-network
    restart: unless-stopped

  backend:
    image: riya9421/mern-task-manager-backend:latest
    container_name: taskmanager-backend
      
    env_file:
      - ./backend/.env  

    expose:
      - "5000"

    depends_on:
      - mongodb

    networks:
      - taskmanager-network
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: taskmanager-mongodb
    volumes:
      - mongodb_data:/data/db

    networks:
      - taskmanager-network
      
    restart: unless-stopped

networks:
  taskmanager-network:
    driver: bridge

volumes:
  mongodb_data:
