kind: Service
apiVersion: v1
metadata:
  name: frontend-service
  namespace: task-manager-ns

spec:
  selector:
    app: task-manager-fe

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # container port
      
  type: ClusterIP
