apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: task-manager-ns

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: riya9421/mern-task-manager-backend:latest

          imagePullPolicy: Always

          ports:
            - containerPort: 5000

          env:
           - name: PORT
             valueFrom:
              configMapKeyRef:
                name: task-manager-configmap
                key: PORT

           - name: NODE_ENV
             valueFrom:
              configMapKeyRef:
                name: task-manager-configmap
                key: NODE_ENV

           - name: MONGODB_URL
             valueFrom:
              configMapKeyRef:
                name: task-manager-configmap
                key: MONGODB_URL

           - name: ACCESS_TOKEN_SECRET
             valueFrom:
              secretKeyRef:
                name: task-manager-secrets
                key: ACCESS_TOKEN_SECRET

          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

          livenessProbe:
            httpGet:
              path: /healthz
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3 

          readinessProbe:
            httpGet:
              path: /readyz
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3   


