apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-backup-pvc
  namespace: task-manager-ns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual-backup
  resources:
    requests:
      storage: 2Gi
